ci:
  skip: [todo]

default_language_version:
  python: python3
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-toml
  - id: check-merge-conflict
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: sort-simple-yaml
  - id: trailing-whitespace
- repo: local
  hooks:
  - id: todo
    name: Check TODO
    language: pygrep
    args: [-i]
    entry: TODO
    types: [text]
    exclude: ^.pre-commit-config.yaml$
- repo: https://github.com/PyCQA/flake8
  rev: 7.2.0
  hooks:
  - id: flake8
    args: [-j8]
    additional_dependencies:
    - flake8-broken-line
    - flake8-bugbear
    - flake8-comprehensions
    - flake8-debugger
    - flake8-isort
    - flake8-pyproject
    - flake8-string-format
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.16.0
  hooks:
  - id: mypy
    additional_dependencies: [types-setuptools, types-requests]
- repo: https://github.com/google/yapf
  rev: v0.43.0
  hooks:
  - id: yapf
    args: [-i]
    additional_dependencies: [toml]
- repo: https://github.com/PyCQA/isort
  rev: 6.0.1
  hooks:
  - id: isort
